---
name: ğŸ¤– Pull Request Labeler

on:
  - pull_request_target # zizmor: ignore[dangerous-triggers]

permissions:
  contents: read

jobs:
  label:
    name: ğŸ·ï¸ Run labeler
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Ensure write access for PRs
    steps:
      - name: Pull Request Labeler
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: '.github/labeler.yml'
          sync-labels: true
