---
name: ğŸ¥‡ First Interaction

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  welcome:
    name: ğŸ‘½ Greetings Earthing
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘‹ğŸ¼ Send Welcome Message
        uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          issue_message: |
            ğŸ‰ **Welcome to Our Chess Project, @{{ github.actor }}!** ğŸ‰

            We are absolutely thrilled to have you join our community!
          pr_message: |
            Your contribution means the world to us,
            and we can't wait to see the amazing things we can achieve together on the chessboard.

            Please feel free to ask questions and share your ideas.
            Remember, every contribution, big or small, makes a significant impact!

            Thank you for being a part of our journey. Letâ€™s create something beautiful together! ğŸŒŸ
